# Generated by Django 4.2.1 on 2023-07-11 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("stock_flow", "0003_alter_part_dispatch_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="PdiCheckList",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("project", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="stock_flow.project")),
            ],
        ),
        migrations.CreateModel(
            name="PdiCheckPoint",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("checkpoint", models.CharField(max_length=300)),
                (
                    "pdi_checklist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="check_points", to="pdi.pdichecklist"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PdiCheckpointPictures",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("picture", models.ImageField(upload_to="media")),
                (
                    "check_point",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="pictures", to="pdi.pdicheckpoint"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PdiAnswer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "answer",
                    models.CharField(
                        choices=[("OK", "OK"), ("NOK", "NOT OK"), ("N/A", "Not Applicable")], max_length=200
                    ),
                ),
                ("comment", models.CharField(max_length=300)),
                (
                    "pdi_check_point",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="answer", to="pdi.pdicheckpoint"
                    ),
                ),
            ],
        ),
    ]
