# Generated by Django 4.2.1 on 2023-07-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pdi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pdianswer",
            name="answer",
            field=models.CharField(
                choices=[("OK", "OK"), ("NOK", "NOT OK"), ("N/A", "NOT APPLICABLE")], max_length=200
            ),
        ),
    ]
