# Generated by Django 4.2.1 on 2023-07-12 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_alter_user_groups_alter_user_user_permissions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="tenant",
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to="accounts.client"),
        ),
    ]
