# Generated by Django 4.2.1 on 2023-07-11 13:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock_flow", "0002_cyclestage_location_partstatus_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="dispatch_date",
            field=models.DateField(blank=True, default="2020-01-01"),
        ),
    ]
