# Generated by Django 4.2.1 on 2023-07-11 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stock_flow", "0003_alter_part_dispatch_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="part",
            name="dispatch_date",
            field=models.DateField(blank=True),
        ),
    ]
